version: '3'

services:
  flask_app:
    build: ./backend
    volumes:
      - ./backend:/user/src/app
    restart: always
    ports: 
      - 80:5000
    container_name: flask_app

  web:
    build: ./frontend
    volumes:
      - ./frontend:/user/src/app
    ports:
      - 3000:3000
    depends_on:
        - flask_app