version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/user/src/app
    restart: always
    ports: 
      - 80:5000

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/user/src/app
    ports:
      - 3000:3000
    depends_on:
        - backend